version: '3' # версия синтаксиса
services:
 express-app: # Сервер Express
    build: .
    ports:
      - '5555:4444'
    depends_on:
      - db
    environment:
      DATABASE_URL: "mongodb+srv://admin:wwwwww@db.rxi8j.mongodb.net/blog?retryWrites=true&w=majority&appName=Cluster0"
 db: # База данных
    image: prismagraphql/mongo-single-replica:5.0.3
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: wwwwww
